name: Pages

on:
  push:
    branches:
      - main  # 如果你的默认分支是 master，请将这里改为 master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 如果你的仓库依赖子模块，请取消下面的注释
          # submodules: recursive

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          # 请将 "20" 替换为你本地使用的 Node.js 主版本号，例如 "18" 或 "22"
          node-version: "24"

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: npm install
             npm install -g hexo-cli

      - name: Build
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
