name: Pages

on:
  push:
    branches:
      - main  # 如果你默认分支是 master 记得改

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"  # 改为你本地的版本号

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-v2  # 加了 -v2 强制刷新
          restore-keys: |
            ${{ runner.OS }}-npm-cache-v2

      - name: Install Dependencies
        run: |
          npm install -g hexo-cli
          rm -rf node_modules   # 删除可能损坏的缓存
          npm install --force   # --force 解决可能的依赖冲突

      - name: Build
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
